#include "Config.h"


Config::Config(int argc, char** argv)
{
	WINDOW_X = 100;
	WINDOW_Y = 100;
	WINDOW_W = 1280;
	WINDOW_H = 720;
	ARGC = argc;
	ARGV = argv;

	WINDOW_DEPTH_BITS = 24;
	WINDOW_STENCIL_BITS = 8;
	WINDOW_ANTIALIASING_LEVEL = 4;
	WINDOW_MAJOR_VERSION = 3;
	WINDOW_MINOR_VERSION = 0;

	BOX2D_POSITION_ITERATIONS = 2;
	BOX2D_VELOCITY_ITERATIONS = 6;
	BOX2D_TIME_STEP = 1.0f / 30.0f;

	NUM_PLAYERS = 2;
	TANKS_PER_PLAYER = 1;
	NUM_TANKS = NUM_PLAYERS * TANKS_PER_PLAYER;
	GRAVITY = -1.0f;
}


Config::~Config()
{
}
